# ------------------------------------------------------------------ #
#                  Configuration for SpeedTracks                     #
# ------------------------------------------------------------------ #

# Define custom speed multipliers for minecarts based on the block
# directly beneath the rail.
#
# The value is a multiplier of Minecraft's default minecart speed.
# 1.0 = Default speed (100%)
# 2.0 = Double speed (200%)
# 0.5 = Half speed (50%)
# 0.0 = Stops the minecart
speed-blocks:
  # Examples for faster travel
  GOLD_BLOCK: 2.0
  DIAMOND_BLOCK: 3.0
  EMERALD_BLOCK: 4.0
  NETHERITE_BLOCK: 6.0

  # Examples for slower travel
  SOUL_SAND: 0.5
  SLIME_BLOCK: 0.25

  # Example for a full stop
  OBSIDIAN: 0.0