name: SpeedTracks
version: '1.0'
main: BasisZock.github.io.speedTracks.SpeedTracks
api-version: '1.21'
author: BasisZock
description: ${description}
commands:
  speedtracks:
    description: Main command for the SpeedTracks plugin.
    aliases: [st]
    usage: /<command> [reload|info]
permissions:
  speedtracks.command.reload:
    description: Allows reloading the SpeedTracks configuration.
    default: op
  speedtracks.command.info:
    description: Allows viewing speed multiplier information.
    default: true